services:
  routing-updater:
    build: .
    container_name: remna-routing-updater
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./template.json:/app/template.json:ro
      - ./output:/app/output
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
